Repository NadzwyczajnaGrupaRobocza/bomberman, pull requests merged in 2019-03, with the labels that each got.

#94 Closes #93 replaced sf::clock by std::high_resolution_clock
  cmake/platforms/Windows.cmake
  src/game/main.cpp
Labels: bug

#91 Closes #90 : introduce color
  .clang-format
  src/game/BombermanGameWorld.cpp
  src/game/BombermanGameWorld.hpp
  src/game/SimpleMap.cpp
  src/game/SimpleMap.hpp
  src/game/SimpleMap.ut.cpp
  src/game/TimeBomb.cpp
  src/game/TimeBomb.hpp
  src/game/TimeBomb.ut.cpp
  src/graphics/core/context_renderer.hpp
  src/graphics/core/render_target.stub.hpp
  src/graphics/core/renderer_pool_sfml.cpp
  src/graphics/core/renderer_pool_sfml.hpp
  src/graphics/core/renderer_pool_sfml.ut.cpp
  src/graphics/core/sfml_rectangle_shape.cpp
  src/graphics/core/sfml_rectangle_shape.hpp
  src/graphics/core/sfml_rectangle_shape.ut.cpp
  src/graphics/core/sfml_render_target.hpp
  src/graphics/core/sfml_render_target.ut.cpp
  src/graphics/core/sfml_window.hpp
  src/graphics/examples/simple_moving_rectangle.cpp
  src/graphics/examples/simple_rectangle_draw.cpp
  src/graphics/includes/graphics/color.hpp
  src/graphics/includes/graphics/renderer_pool.hpp
  src/graphics/includes/graphics/renderer_pool.mock.hpp
Labels: Task

#83 Add dockerfile for development
  Dockerfile.dev
  docs/dev/UsingDocker.md
Labels: Documentation, enhancement

#102 Very little delta doesn't accumulate
  src/game/TimeBomb.cpp
  src/game/TimeBomb.hpp
  src/game/TimeBomb.ut.cpp
Labels: bug
